#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Expose a repo's .claude/ skills to other agent harnesses.

`.claude/` stays the single source of truth. Every file this writes is a *pointer*
back into it, never a copy, so nothing can drift out of sync silently.

    sync_harnesses.py --harness codex,openhands   # first run: choose harnesses
    sync_harnesses.py                             # regenerate
    sync_harnesses.py --check                     # exit 1 + diff if stale

The chosen harnesses persist in .agents/harnesses.json so later runs and CI need no
flags. Run with `uv run` (deps are declared above) or with any python3 that has pyyaml.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("needs pyyaml — run via `uv run sync_harnesses.py` or `pip install pyyaml`")

MARKER = "generated by the agent-harness skill — do not edit by hand"
CONFIG = Path(".agents/harnesses.json")
SKILLS_LINK = Path(".agents/skills")
SKILLS_TARGET = Path("../.claude/skills")
MAX_DESCRIPTION = 1024  # agentskills.io/specification
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
STOPWORDS = {"the", "and", "for", "use", "when", "with", "a", "an", "to"}


@dataclass
class Artifact:
    kind: str  # skill | command | agent
    name: str
    path: Path  # repo-relative path to the canonical .claude/ file
    description: str
    applies_to: str = "**"
    triggers: list[str] = field(default_factory=list)


# --- parsing -------------------------------------------------------------------


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        sys.exit(f"{path}: missing YAML frontmatter")
    try:
        _, raw, _ = text.split("---", 2)
    except ValueError:
        sys.exit(f"{path}: unterminated YAML frontmatter")
    try:
        data = yaml.safe_load(raw) or {}
    except yaml.YAMLError as exc:
        sys.exit(f"{path}: unparseable frontmatter: {exc}")
    if not isinstance(data, dict):
        sys.exit(f"{path}: frontmatter is not a mapping")
    return data


def validate_name(name: str, path: Path) -> str:
    """Names become directory and file names, so an unvalidated one is a path
    traversal: pathlib lets an absolute component replace the whole path, and
    '..' walks out of the repo entirely."""
    if not name:
        sys.exit(f"{path}: 'name' is required")
    if not NAME_RE.match(name) or len(name) > 64:
        sys.exit(f"{path}: name '{name}' violates the Agent Skills name rules")
    return name


def safe_target(root: Path, rel: Path) -> Path:
    """Last line of defence for every write and delete, including future emitters."""
    target = (root / rel).resolve()
    if not target.is_relative_to(root.resolve()):
        sys.exit(f"refusing to touch a path outside the repo: {rel}")
    return target


def clean_description(text: str) -> str:
    """Distil a Claude description into one another harness can use.

    Claude agent descriptions embed <example> blocks narrating Task-tool usage that
    means nothing elsewhere. Drop them, flatten, and cap at the spec limit.
    """
    text = text.replace("\\n", "\n")
    text = re.split(r"\n\s*Examples?:\s*", text)[0]
    text = re.sub(r"<example>.*?</example>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = " ".join(text.split())
    text = re.sub(r"\s*Examples?:\s*$", "", text)
    if len(text) > MAX_DESCRIPTION:
        text = text[: MAX_DESCRIPTION - 1].rsplit(" ", 1)[0] + "…"
    return text


def derive_triggers(name: str, description: str, override: str | None) -> list[str]:
    """Keyword list for harnesses that match on triggers rather than model judgment."""
    if override:
        return [t.strip() for t in override.split(",") if t.strip()]
    triggers = {name, *(w for w in name.split("-") if w not in STOPWORDS and len(w) > 2)}
    for quoted in re.findall(r"[\"'“]([^\"'”]{3,40})[\"'”]", description):
        triggers.add(quoted.strip().lower())
    for code in re.findall(r"`([^`]{3,40})`", description):
        triggers.add(code.strip().lower())
    return sorted(triggers)


def load_artifacts(root: Path) -> dict[str, list[Artifact]]:
    found: dict[str, list[Artifact]] = {"skill": [], "command": [], "agent": []}

    for skill_md in sorted(root.glob(".claude/skills/*/SKILL.md")):
        fm = parse_frontmatter(skill_md)
        directory = skill_md.parent.name
        name = str(fm.get("name") or "").strip()
        description = str(fm.get("description") or "").strip()
        validate_name(name, skill_md)
        if not description:
            sys.exit(f"{skill_md}: 'description' is required and must be non-empty")
        if name != directory:
            sys.exit(f"{skill_md}: name '{name}' must match its directory '{directory}'")
        meta = fm.get("metadata") if isinstance(fm.get("metadata"), dict) else {}
        found["skill"].append(
            Artifact(
                kind="skill",
                name=name,
                path=skill_md.relative_to(root),
                description=clean_description(description),
                applies_to=str(meta.get("applies-to") or "**"),
                triggers=derive_triggers(name, description, meta.get("triggers")),
            )
        )

    for kind, pattern in (("command", ".claude/commands/*.md"), ("agent", ".claude/agents/*.md")):
        for md in sorted(root.glob(pattern)):
            fm = parse_frontmatter(md)
            description = clean_description(str(fm.get("description") or "").strip())
            if not description:
                sys.exit(f"{md}: 'description' is required to generate a pointer")
            found[kind].append(
                Artifact(
                    kind=kind,
                    # Unlike skills, these have no directory to be checked against,
                    # so the charset rule is the only thing keeping the name from
                    # becoming an arbitrary write path.
                    name=validate_name(str(fm.get("name") or md.stem).strip(), md),
                    path=md.relative_to(root),
                    description=description,
                )
            )

    if not found["skill"]:
        sys.exit("no skills under .claude/skills — refusing to generate an empty mapping")
    return found


# --- emitters: one per harness -------------------------------------------------
#
# Every emitter returns {repo-relative path: content} and emits POINTERS ONLY.
# Repo conventions belong in AGENTS.md, which each of these harnesses already
# reads; restating them per file would be duplication that can drift.

def q(value: str) -> str:
    """Quote a scalar for YAML frontmatter. JSON strings are valid YAML."""
    return json.dumps(value)


INLINE_NOTE = (
    "This is a subagent procedure. If this harness has no subagent delegation, "
    "run the procedure inline in the current session."
)


def emit_codex(arts: dict[str, list[Artifact]]) -> dict[Path, str]:
    """Codex reads .agents/skills natively; only non-skill artifacts need adapters."""
    out = {}
    for art in arts["command"] + arts["agent"]:
        note = f"\n{INLINE_NOTE}\n" if art.kind == "agent" else ""
        out[Path(".codex/skills") / art.name / "SKILL.md"] = f"""---
name: {art.name}
description: {q(art.description)}
---

<!-- {MARKER} -->

# {art.name}

Canonical source: `{art.path}` — read that file and follow it. This pointer exists
only because this harness does not read `.claude/`.
{note}
Repo-wide conventions are in `AGENTS.md`.
"""
    return out


def emit_openhands(arts: dict[str, list[Artifact]]) -> dict[Path, str]:
    """OpenHands reads flat microagents with `triggers`, not SKILL.md directories."""
    base = Path(".openhands/microagents")
    out = {}

    def table(items):
        if not items:
            return "| _none_ | | |"
        return "\n".join(f"| `{a.name}` | {a.description} | `{a.path}` |" for a in items)

    out[base / "repo.md"] = f"""---
name: repo
---

<!-- {MARKER} -->

# Repository knowledge

Conventions live in `.claude/`, the single source of truth; `AGENTS.md` holds the
repo-wide rules. The tables below are an index. When a task matches an entry, read the
linked file before acting — never rely on this summary alone.

## Skills

| skill | when to use | canonical path |
| --- | --- | --- |
{table(arts["skill"])}

## Runbooks (slash commands)

| runbook | what it does | canonical path |
| --- | --- | --- |
{table(arts["command"])}

## Procedures (subagents)

Run these inline — this harness has no subagent delegation.

| procedure | what it does | canonical path |
| --- | --- | --- |
{table(arts["agent"])}
"""

    for art in arts["skill"]:
        out[base / f"{art.name}.md"] = f"""---
name: {art.name}
triggers: {json.dumps(art.triggers)}
---

<!-- {MARKER} -->

{art.description}

Read `{art.path}` before acting on the above — it is the canonical source and this file
is only a pointer. Resolve relative paths against `{art.path.parent}`.
"""
    return out


def emit_copilot(arts: dict[str, list[Artifact]]) -> dict[Path, str]:
    """Copilot loads path-scoped instruction files matching `applyTo` globs."""
    out = {}
    for art in arts["skill"]:
        out[Path(".github/instructions") / f"{art.name}.instructions.md"] = f"""---
applyTo: {q(art.applies_to)}
---

<!-- {MARKER} -->

# {art.name}

{art.description}

Canonical source: `{art.path}`. Read it before making changes in scope; this file is a
pointer, not a summary to rely on. Repo-wide conventions are in `AGENTS.md`.
"""
    index = "\n".join(f"- **{a.name}** — {a.description} See `{a.path}`." for a in arts["skill"])
    out[Path(".github/copilot-instructions.md")] = f"""<!-- {MARKER} -->

# Copilot guidance

Project conventions are canonical in `.claude/skills/`; repo-wide rules are in
`AGENTS.md`. Update those, never this file.

{index}
"""
    return out


def emit_cursor(arts: dict[str, list[Artifact]]) -> dict[Path, str]:
    """Cursor reads .mdc rules with `globs` + `alwaysApply`."""
    out = {}
    for art in arts["skill"]:
        out[Path(".cursor/rules") / f"{art.name}.mdc"] = f"""---
description: {q(art.description)}
globs: {q(art.applies_to)}
alwaysApply: false
---

<!-- {MARKER} -->

Canonical source: `{art.path}` — read it before acting. This rule is a pointer only.
Repo-wide conventions are in `AGENTS.md`.
"""
    return out


EMITTERS = {
    "codex": emit_codex,
    "openhands": emit_openhands,
    "copilot": emit_copilot,
    "cursor": emit_cursor,
}
# Directories an emitter owns, scanned for orphaned generated files.
OWNED = {
    "codex": [Path(".codex/skills")],
    "openhands": [Path(".openhands/microagents")],
    "copilot": [Path(".github/instructions"), Path(".github/copilot-instructions.md")],
    "cursor": [Path(".cursor/rules")],
}


# --- filesystem ----------------------------------------------------------------


def find_root(start: Path) -> Path:
    for parent in [start.resolve(), *start.resolve().parents]:
        if (parent / ".claude").is_dir():
            return parent
    sys.exit(f"no ancestor of {start} contains a .claude/ directory")


def read_config(root: Path) -> list[str]:
    path = root / CONFIG
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        sys.exit(f"{CONFIG}: {exc}")
    return [h for h in data.get("harnesses", []) if h in EMITTERS]


def write_config(root: Path, harnesses: list[str]) -> None:
    path = root / CONFIG
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"harnesses": sorted(harnesses)}, indent=2) + "\n", encoding="utf-8")


def ensure_symlink(root: Path, check: bool) -> list[str]:
    link = root / SKILLS_LINK
    if link.is_symlink():
        if Path(link.readlink()) == SKILLS_TARGET:
            return []
        if check:
            return [f"{SKILLS_LINK} points at {link.readlink()}, expected {SKILLS_TARGET}"]
        link.unlink()
    elif link.exists():
        # Never delete something a human may have created deliberately.
        sys.exit(f"{SKILLS_LINK} exists and is not a symlink — move it aside and re-run")
    elif check:
        return [f"{SKILLS_LINK} is missing"]
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(SKILLS_TARGET)
    return []


def find_orphans(root: Path, planned: set[Path]) -> list[Path]:
    """Scan every harness's directories, not just the configured ones.

    Dropping a harness from the config must prune what it wrote; scanning only the
    active list would strand those files, and a stale pointer keeps feeding an agent
    guidance that no longer matches the repo. Only marker-bearing files are eligible,
    so hand-written content in a shared directory like .github/ is never touched.
    """
    orphans = []
    for harness in OWNED:
        for owned in OWNED[harness]:
            target = root / owned
            candidates = [target] if target.is_file() else sorted(target.rglob("*")) if target.is_dir() else []
            for path in candidates:
                if not path.is_file():
                    continue
                rel = path.relative_to(root)
                if rel not in planned and MARKER in path.read_text(encoding="utf-8", errors="ignore"):
                    orphans.append(rel)
    return orphans


def main() -> int:
    parser = argparse.ArgumentParser(description="Map .claude/ skills onto other agent harnesses.")
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    parser.add_argument("--harness", help=f"comma-separated: {', '.join(EMITTERS)}")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="repo root (default: cwd)")
    args = parser.parse_args()

    root = find_root(args.root)
    harnesses = read_config(root)
    if args.harness:
        requested = [h.strip() for h in args.harness.split(",") if h.strip()]
        unknown = [h for h in requested if h not in EMITTERS]
        if unknown:
            sys.exit(f"unknown harness(es): {', '.join(unknown)}. Known: {', '.join(EMITTERS)}")
        harnesses = requested
    if not harnesses:
        sys.exit(f"no harnesses configured — run once with --harness {','.join(EMITTERS)}")

    arts = load_artifacts(root)
    plan: dict[Path, str] = {}
    for harness in harnesses:
        plan.update(EMITTERS[harness](arts))

    problems = ensure_symlink(root, args.check)
    for rel in find_orphans(root, set(plan)):
        problems.append(f"orphaned generated file: {rel}")
        if not args.check:
            victim = safe_target(root, rel)
            victim.unlink()
            parent = victim.parent
            if parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()

    for rel, content in sorted(plan.items()):
        target = safe_target(root, rel)
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == content:
            continue
        if args.check:
            problems.append(
                "\n".join(
                    difflib.unified_diff(
                        current.splitlines(), content.splitlines(),
                        fromfile=f"{rel} (on disk)", tofile=f"{rel} (expected)", lineterm="",
                    )
                )
                if current
                else f"missing: {rel}"
            )
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    if read_config(root) != sorted(harnesses):
        if args.check:
            problems.append(f"{CONFIG} does not match the requested harnesses")
        else:
            write_config(root, harnesses)

    counts = ", ".join(f"{len(v)} {k}s" for k, v in arts.items())
    if args.check:
        if problems:
            print("\n".join(problems))
            print(f"\nagent-harness is STALE — run {Path(__file__).name} to repair.")
            return 1
        print(f"agent-harness is up to date ({counts}; {', '.join(harnesses)}).")
        return 0

    if problems:
        print("\n".join(problems))
    print(f"agent-harness synced: {counts} → {len(plan)} files for {', '.join(harnesses)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
