"""These checks guard the properties that make the mapping trustworthy: it never
copies content, never silently drifts, and never deletes something a human wrote.
A regression in any of them is invisible at runtime — the agent just quietly stops
seeing the repo's skills, or starts following a stale copy of them."""

import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "sync_harnesses.py"


def run(repo, *args):
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--root", str(repo), *args],
        capture_output=True, text=True,
    )


@pytest.fixture
def repo(tmp_path):
    """A minimal repo: two skills, one command, one agent."""
    skills = tmp_path / ".claude/skills"
    (skills / "brand").mkdir(parents=True)
    (skills / "brand" / "SKILL.md").write_text(
        "---\nname: brand\ndescription: Brand rules. Triggers \"design tokens\".\n"
        "metadata:\n  applies-to: src/**/*.tsx\n---\n\nBody\n"
    )
    (skills / "database").mkdir(parents=True)
    (skills / "database" / "SKILL.md").write_text(
        "---\nname: database\ndescription: DB layer.\n---\n\nBody\n"
    )
    commands = tmp_path / ".claude/commands"
    commands.mkdir(parents=True)
    (commands / "db-setup.md").write_text("---\ndescription: Set up the DB.\n---\n\nRunbook\n")
    agents = tmp_path / ".claude/agents"
    agents.mkdir(parents=True)
    (agents / "db-agent.md").write_text(
        "---\nname: db-agent\ndescription: 'Does DB work.\\n\\nExamples:\\n\\n"
        "<example>\\nuser: \"x\"\\n</example>'\n---\n\nProcedure\n"
    )
    return tmp_path


def test_symlink_is_relative_and_correct(repo):
    assert run(repo, "--harness", "codex").returncode == 0
    link = repo / ".agents/skills"
    assert link.is_symlink()
    assert link.readlink() == Path("../.claude/skills")
    assert (link / "brand" / "SKILL.md").exists()


def test_sync_is_idempotent(repo):
    run(repo, "--harness", "codex,openhands,copilot,cursor")
    result = run(repo, "--check")
    assert result.returncode == 0, result.stdout


def test_config_persists_so_later_runs_need_no_flags(repo):
    run(repo, "--harness", "openhands")
    assert '"openhands"' in (repo / ".agents/harnesses.json").read_text()
    assert run(repo, "--check").returncode == 0


def test_refuses_to_run_with_no_harness_configured(repo):
    result = run(repo)
    assert result.returncode != 0
    assert "no harnesses configured" in result.stderr


def test_deleted_file_is_detected_and_repaired(repo):
    run(repo, "--harness", "openhands")
    target = repo / ".openhands/microagents/brand.md"
    target.unlink()
    stale = run(repo, "--check")
    assert stale.returncode == 1
    assert "brand.md" in stale.stdout
    run(repo)
    assert target.exists()
    assert run(repo, "--check").returncode == 0


def test_orphan_is_reported_then_pruned(repo):
    run(repo, "--harness", "codex")
    orphan = repo / ".codex/skills/gone/SKILL.md"
    orphan.parent.mkdir(parents=True)
    orphan.write_text("---\nname: gone\ndescription: x\n---\n\n"
                      "<!-- generated by the agent-harness skill — do not edit by hand -->\n")
    assert run(repo, "--check").returncode == 1
    run(repo)
    assert not orphan.exists()
    assert not orphan.parent.exists()


def test_hand_written_file_in_owned_dir_is_left_alone(repo):
    """Only files carrying the marker are ours to delete."""
    run(repo, "--harness", "codex")
    mine = repo / ".codex/skills/handwritten/SKILL.md"
    mine.parent.mkdir(parents=True)
    mine.write_text("---\nname: handwritten\ndescription: mine\n---\n\nKeep me\n")
    run(repo)
    assert mine.exists()


def test_refuses_to_clobber_a_real_directory(repo):
    (repo / ".agents/skills").mkdir(parents=True)
    result = run(repo, "--harness", "codex")
    assert result.returncode != 0
    assert "not a symlink" in result.stderr
    assert (repo / ".agents/skills").is_dir()


def test_name_must_match_directory(repo):
    (repo / ".claude/skills/brand/SKILL.md").write_text(
        "---\nname: wrong\ndescription: x\n---\n\nBody\n"
    )
    result = run(repo, "--harness", "codex")
    assert result.returncode != 0
    assert "must match its directory" in result.stderr


@pytest.mark.parametrize(
    "evil_name",
    ["/tmp/pwned-abs", "../../../../tmp/pwned-rel", "a/b", "..", "UPPER", "trailing-"],
)
def test_name_cannot_escape_the_repo(repo, evil_name, tmp_path):
    """Commands and agents have no directory to be validated against, so the
    charset rule is all that stops `name` from becoming an arbitrary write path.
    pathlib silently lets an absolute component replace the whole path."""
    (repo / ".claude/agents/db-agent.md").write_text(
        f"---\nname: {evil_name}\ndescription: evil\n---\n\nx\n"
    )
    result = run(repo, "--harness", "codex")
    assert result.returncode != 0
    assert "violates the Agent Skills name rules" in result.stderr
    escaped = [p for p in tmp_path.rglob("pwned*")] + [Path("/tmp/pwned-abs")]
    assert not any(p.exists() for p in escaped)


def test_description_cannot_inject_frontmatter_keys(repo):
    """A description with a quote and newline must not add keys to the generated
    frontmatter — allowed-tools in particular is security-relevant."""
    yaml = pytest.importorskip("yaml")
    (repo / ".claude/agents/db-agent.md").write_text(
        '---\nname: sneaky\ndescription: "Use when: x\\" \\nallowed-tools: Bash(rm:*)"\n---\n\nx\n'
    )
    assert run(repo, "--harness", "codex").returncode == 0
    text = (repo / ".codex/skills/sneaky/SKILL.md").read_text()
    front = yaml.safe_load(text.split("---")[1])
    assert sorted(front) == ["description", "name"]


def test_missing_description_is_fatal(repo):
    (repo / ".claude/skills/database/SKILL.md").write_text("---\nname: database\n---\n\nBody\n")
    result = run(repo, "--harness", "codex")
    assert result.returncode != 0
    assert "description" in result.stderr


def test_claude_example_blocks_are_stripped_from_descriptions(repo):
    yaml = pytest.importorskip("yaml")
    run(repo, "--harness", "codex")
    text = (repo / ".codex/skills/db-agent/SKILL.md").read_text()
    assert "<example>" not in text
    assert "Examples:" not in text
    assert yaml.safe_load(text.split("---")[1])["description"] == "Does DB work."


def test_generated_files_point_rather_than_copy(repo):
    """The body of every skill is 'Body'; no emitter may inline it."""
    run(repo, "--harness", "codex,openhands,copilot,cursor")
    generated = [p for p in repo.rglob("*") if p.is_file() and ".claude" not in p.parts]
    assert generated
    for path in generated:
        if path.name == "harnesses.json":
            continue
        text = path.read_text()
        assert "Body" not in text, f"{path} inlined skill content"
        # Pointing means naming a canonical path under .claude/ — skills, commands,
        # or agents, depending on what the file adapts.
        assert ".claude/" in text, f"{path} does not point back at .claude/"


def test_copilot_and_cursor_carry_scope_from_metadata(repo):
    yaml = pytest.importorskip("yaml")

    def front(path):
        return yaml.safe_load(path.read_text().split("---")[1])

    run(repo, "--harness", "copilot,cursor")
    assert front(repo / ".github/instructions/brand.instructions.md")["applyTo"] == "src/**/*.tsx"
    assert front(repo / ".cursor/rules/brand.mdc")["globs"] == "src/**/*.tsx"
    # A skill without metadata falls back to matching everything.
    assert front(repo / ".cursor/rules/database.mdc")["globs"] == "**"


def test_openhands_index_lists_every_artifact_kind(repo):
    run(repo, "--harness", "openhands")
    index = (repo / ".openhands/microagents/repo.md").read_text()
    for name in ("brand", "database", "db-setup", "db-agent"):
        assert f"`{name}`" in index


def test_switching_harnesses_prunes_the_old_one(repo):
    """Dropping a harness must remove what it wrote. A lingering pointer keeps
    feeding an agent guidance that no longer reflects the repo."""
    run(repo, "--harness", "openhands,copilot")
    assert (repo / ".openhands/microagents/repo.md").exists()
    assert (repo / ".github/copilot-instructions.md").exists()

    run(repo, "--harness", "codex")
    assert not (repo / ".openhands/microagents/repo.md").exists()
    assert not (repo / ".github/copilot-instructions.md").exists()
    assert not (repo / ".github/instructions/brand.instructions.md").exists()
    assert (repo / ".codex/skills/db-agent/SKILL.md").exists()
    assert run(repo, "--check").returncode == 0


def test_pruning_never_touches_hand_written_github_content(repo):
    """.github/ is shared with CI and templates, so only marker-bearing files
    may be removed from it."""
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "ci.yml").write_text("name: CI\non: push\n")
    (repo / ".github/PULL_REQUEST_TEMPLATE.md").write_text("# hand written\n")

    run(repo, "--harness", "copilot")
    run(repo, "--harness", "codex")  # drops copilot, triggering a prune of .github

    assert (workflows / "ci.yml").exists()
    assert (repo / ".github/PULL_REQUEST_TEMPLATE.md").exists()
