#set prefix to ctrl space
unbind C-b
set -g prefix C-Space
bind Space send-prefix

#reload config
bind-key r source-file ~/.tmux.conf \; display "Reloaded from ~/.tmux.conf"

#set j and k to page up and up (vim keys for scrolling)
setw -g mode-keys vi
set -g status-keys vi


#ctrl d and ctrl u for page up and page down in history
bind-key -t vi-edit Up history-up
bind-key -t vi-edit Down history-down

#pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key q display-panes

#window navigation
bind-key C-a last-window
bind-key c new-window
bind-key t next-window
bind-key T previous-window

#press shift wtih mouse to copy
#copy text to clipboard
#move x clipboard into tmux paste buffer
#bind C-p run "tmux set-buffer \"$(xclip -o)\"; tmux paste buffer"
#bind C-y run "tmux save-buffer - | xclip -i"

#unbind -T copy-mode MouseDragEnd1Panea
#bind-key -T copymode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace-pbcopy"
#bind-key -t vi-copy MouseDragEnd1Pane copy-pipe "xclip -in -selection clipboard"
#bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
#bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
#copy mode
#bind-key Escape copy-mode
#bind-key Enter copy-mode
bind-key ] paste-buffer

#bind vi-copy MouseDragEnd1Pane copy-selection -x 
#bind-key -t vi-copy MouseDragEnd1Pane copy-selection -x 
#bind-key -t emacs-copy MouseDragEnd1Pane copy-selection -x
#unbind -T copy-mode-vi MouseDragEnd1Pane

if-shell -b '[ "$(echo "$TMUX_VERSION <= 2.3" | bc) = 1 ]' \
    'bind-key -t vi-copy "v" begin-selection; \
     bind-key -t vi-copy "y" copy-selection; \
     bind-key -t vi-copy "r" rectangle-toggle;\
    '

#if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.4" | bc)" = 1 ]' \
#    'bind -T copy-mode-vi "v" send-keys -X begin-selection; \ 
#     bind -T copy-mode-vi "y" send-keys -X copy-pipe-and-cancel "pbcopy"; \
#    '
    
#bind-key 'p' run-shell "pbpaste | tmux load-buffer - && tmux paste-buffer"

set-option -g default-terminal "screen-256color"
set -g history-limit 500000
set -g mouse on
#set -g mouse-mode on

source /usr/share/powerline/bindings/tmux/powerline.conf

set -g base-index 1
set-window-option -g automatic-rename on
setw -g monitor-activity on
