context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "Arctis Noise Cancelling"
      media.name       = "Arctis Noise Cancelling"
      filter.graph = {
        nodes = [
          {
            type   = ladspa
            name   = rnnoise
            plugin = /usr/lib/ladspa/librnnoise_ladspa.so
            label  = noise_suppressor_mono
            control = {
              "VAD Threshold (%)"          = 50.0
              "VAD Grace Period (ms)"      = 200
              "Retroactive VAD Grace (ms)" = 0
            }
          }
        ]
      }
      capture.props = {
        node.name      = "capture.arctis_denoise"
        node.passive   = true
        audio.rate     = 48000
        audio.channels = 1
        audio.position = [ MONO ]
        target.object  = "alsa_input.usb-SteelSeries_Arctis_Nova_Pro_Wireless-00.mono-fallback"
      }
      playback.props = {
        node.name        = "arctis_denoise_source"
        node.description = "Arctis Noise Cancelling"
        media.class      = Audio/Source
        audio.rate       = 48000
        audio.channels   = 1
        audio.position   = [ MONO ]
      }
    }
  }
]
