from pathlib import Path

import pytest

import extract_comments as ec


def write(tmp_path, name, text):
    target = tmp_path / name
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    return target


def skips(target):
    return {c["text"]: c["skip"] for c in ec.extract(target)["comments"]}


def test_generated_marker_skips_the_whole_file(tmp_path):
    target = write(tmp_path, "z.go", "// Code generated by protoc. DO NOT EDIT.\n// x\n")
    assert ec.extract(target)["skipped"] == "generated"


def test_vendor_path_skips_the_whole_file(tmp_path, monkeypatch):
    """Directory-shaped patterns are only trustworthy once the path is known
    relative to the repo root (see FINDING 5 in the fix-round report) -- chdir
    into tmp_path so `vendor/lib/z.go` is relativizable, the normal shape a
    caller passing repo-relative paths (e.g. from `git diff --name-only`)
    would produce."""
    monkeypatch.chdir(tmp_path)
    target = write(tmp_path, "vendor/lib/z.go", "// x\n")
    assert ec.extract(target)["skipped"] == "excluded-path"


def test_fixture_path_skips_the_whole_file(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    target = write(tmp_path, "testdata/z.go", "// x\n")
    assert ec.extract(target)["skipped"] == "excluded-path"


def test_snapshot_suffix_skips_the_whole_file(tmp_path):
    """Vacuous-test fix: this used to accept `unknown-language` too, which
    means it passed even if the `.snap` pattern were deleted outright (a
    `.snap` file has no known language either way). Assert the exact reason."""
    target = write(tmp_path, "a.snap", "// x\n")
    assert ec.extract(target)["skipped"] == "excluded-path"


def test_first_two_lines_are_position_locked(tmp_path):
    target = write(tmp_path, "s.sh", "#!/usr/bin/env bash\n# -*- coding: utf-8 -*-\n# free\n")
    result = skips(target)
    assert result["#!/usr/bin/env bash"] == "position-locked"
    assert result["# -*- coding: utf-8 -*-"] == "position-locked"
    assert result["# free"] is None


def test_nolint_directive_is_protected(tmp_path):
    target = write(tmp_path, "z.go", "package p\n\nvar x = 1 //nolint:errcheck\n")
    assert skips(target)["//nolint:errcheck"] == "directive"


def test_eslint_disable_is_protected(tmp_path):
    target = write(tmp_path, "z.ts", "let a = 1;\n\n// eslint-disable-next-line no-eval\n")
    assert skips(target)["// eslint-disable-next-line no-eval"] == "directive"


def test_coverage_pragma_is_protected(tmp_path):
    target = write(tmp_path, "z.py", "x = 1\n\nif x:  # pragma: no cover\n    pass\n")
    assert skips(target)["# pragma: no cover"] == "directive"


def test_goose_migration_marker_is_protected(tmp_path):
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n-- +goose Down\nDROP TABLE t;\n")
    assert skips(target)["-- +goose Down"] == "directive"


def test_sqlc_name_header_is_protected(tmp_path):
    target = write(tmp_path, "q.sql", "SELECT 1;\n\n-- name: GetUser :one\n")
    assert skips(target)["-- name: GetUser :one"] == "directive"


def test_kubebuilder_marker_is_protected(tmp_path):
    target = write(tmp_path, "t.go", "package p\n\n// +kubebuilder:validation:Required\n")
    assert skips(target)["// +kubebuilder:validation:Required"] == "directive"


def test_doctest_marker_protects_the_docstring(tmp_path):
    target = write(tmp_path, "d.py", 'x = 1\n\n\ndef f():\n    """Doc.\n\n    >>> f()\n    1\n    """\n')
    assert any(v == "test-oracle" for v in skips(target).values())


def test_go_output_marker_protects_the_comment(tmp_path):
    target = write(tmp_path, "e.go", "package p\n\n// Output:\n// 42\n")
    assert skips(target)["// Output:"] == "test-oracle"


def test_spdx_and_licence_are_protected(tmp_path):
    """Vacuous-test fix: both licence lines used to sit in the first two lines,
    inside the position-locked shadow, so `LICENCE_PATTERN` could be deleted
    entirely without failing this test. Move them below line 2 and assert the
    exact reason."""
    target = write(tmp_path, "l.go",
                    "package p\n\n// SPDX-License-Identifier: MIT\n// Copyright 2026 X\n")
    result = skips(target)
    assert result["// SPDX-License-Identifier: MIT"] == "licence"
    assert result["// Copyright 2026 X"] == "licence"


def test_protected_prefix_note_is_marked_not_deletable(tmp_path):
    target = write(tmp_path, "n.go", "package p\n\n// NOTE: retry twice, upstream 502s\n")
    assert skips(target)["// NOTE: retry twice, upstream 502s"] == "protected-prefix"


def test_ordinary_comment_is_not_skipped(tmp_path):
    target = write(tmp_path, "p.go", "package p\n\n// ordinary explanation\n")
    assert skips(target)["// ordinary explanation"] is None


def test_the_plugins_own_samples_are_not_excluded():
    """tests/samples/ must stay outside the skip patterns. When the directory was
    named fixtures/ it matched, and every extractor assertion silently went vacuous."""
    import paths
    assert ec.file_skip_reason(paths.SAMPLES / "sample.go", "") is None


def test_a_fixtures_path_is_still_excluded(tmp_path, monkeypatch):
    """The pattern itself is correct and spec-mandated -- only our own directory
    name was wrong. Chdir'd into tmp_path so the path is relativizable -- see
    FINDING 5: an absolute path that cannot be related to cwd only gets
    filename-shaped patterns, and `fixtures/` is directory-shaped."""
    monkeypatch.chdir(tmp_path)
    assert ec.file_skip_reason(tmp_path / "fixtures" / "z.go", "") == "excluded-path"


def test_a_repo_living_under_a_skip_named_directory_is_not_skipped(tmp_path, monkeypatch):
    """A checkout at ~/build/proj must not skip every file in itself."""
    repo = tmp_path / "build" / "proj" / "pkg"
    repo.mkdir(parents=True)
    target = repo / "z.go"
    target.write_text("package p\n\n// ordinary\n")
    monkeypatch.chdir(repo.parent)
    assert ec.extract(target)["skipped"] is None


def test_dockerfile_syntax_directive_is_protected(tmp_path):
    target = write(tmp_path, "Dockerfile.sh", "# syntax=docker/dockerfile:1\n# free\n")
    assert skips(target)["# syntax=docker/dockerfile:1"] == "position-locked"


# --- Fix round: six Critical/Important findings from code review. ---------


def test_cgo_export_directive_without_a_colon_is_protected(tmp_path):
    """FINDING 1: cgo's export directive has no colon (`//export MyFunc`), but
    the original pattern required `(?:go|export)\\s*:`, so deleting it would
    silently drop a C export."""
    target = write(tmp_path, "z.go", "package p\n\n//export MyFunc\n")
    assert skips(target)["//export MyFunc"] == "directive"


def test_go_embed_directive_still_requires_its_colon(tmp_path):
    """Regression guard for FINDING 1's fix: splitting `export` off from `go:`
    must not stop `//go:embed` from matching."""
    target = write(tmp_path, "z.go", "package p\n\n//go:embed data/*\n")
    assert skips(target)["//go:embed data/*"] == "directive"


def test_sourcemap_comment_with_hash_marker_is_protected(tmp_path):
    """FINDING 2: real sourcemap comments have a literal `#` between the
    comment opener and `sourceMappingURL` (`//# sourceMappingURL=x.map`). The
    outer opener's `\\s*` cannot consume that `#`, so the alternative was
    unreachable for the actual syntax."""
    target = write(tmp_path, "z.ts", "let a = 1;\n\n//# sourceMappingURL=x.map\n")
    assert skips(target)["//# sourceMappingURL=x.map"] == "directive"


def test_sql_optimizer_hint_comment_is_protected(tmp_path):
    """FINDING 3: `/*+ INDEX(t idx) */` is a SQL optimizer hint. The outer
    opener group already consumes `/*`, so the old `/\\*[!+]` alternative
    could never match -- it was dead code."""
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n/*+ INDEX(t idx) */\n")
    assert skips(target)["/*+ INDEX(t idx) */"] == "directive"


def test_mysql_version_gated_comment_is_protected(tmp_path):
    """FINDING 4: `/*!50001 col */` is a MySQL version-gated comment; its
    contents are executed as SQL, so rewording it changes what the database
    runs. Same dead-code root cause as FINDING 3."""
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n/*!50001 col */\n")
    assert skips(target)["/*!50001 col */"] == "directive"


@pytest.mark.parametrize("directory", (
    "build", "dist", "out", "gen", "vendor", "testdata",
))
def test_unrelativizable_absolute_path_does_not_skip_the_whole_repo(directory):
    """FINDING 5: reproduces the coordinator's repro exactly, parametrized
    over several directory-shaped pattern names (round 2, minor item: the
    original test covered only `build`, one of roughly thirteen). Called on
    an absolute path whose ancestry cannot be related to cwd (no chdir here
    -- this test's own cwd is the plugin's checkout, unrelated to
    /tmp/<directory>/...), a directory-shaped pattern like `(^|/)build/`
    must not fire: doing so would silently skip the entire repository,
    reporting a clean sweep."""
    target = f"/tmp/{directory}/proj/pkg/z.go"
    assert ec.file_skip_reason(target, "") is None


def test_unrelativizable_absolute_snap_path_is_still_skipped():
    """FINDING 5, other half: filename-shaped patterns (like `.snap$`) are
    safe even when the path cannot be related to cwd, since they identify the
    file itself rather than an ancestor directory."""
    assert ec.file_skip_reason("/tmp/unrelated/dir/x.snap", "") == "excluded-path"


def test_go_deprecated_convention_is_protected(tmp_path):
    """FINDING 6: `// Deprecated: use X` (the Go convention, no leading `@`)
    used to return None -- there was no alternative for it at all."""
    target = write(tmp_path, "z.go", "package p\n\n// Deprecated: use X\n")
    assert skips(target)["// Deprecated: use X"] == "directive"


def test_jsdoc_deprecated_tag_is_protected(tmp_path):
    """FINDING 6, other half: the `@deprecated` alternative had a stray
    lookahead (`deprecated\\b(?=.*@)`) demanding a second, unrelated `@`
    somewhere later in the text, making it unreachable for ordinary usage."""
    target = write(tmp_path, "z.ts", "let a = 1;\n\n// @deprecated old API\n")
    assert skips(target)["// @deprecated old API"] == "directive"


# --- Round 2: the bare `[!+]` fix for FINDINGS 3/4 was too broad. ----------


def test_rust_inner_doc_comment_is_reviewable_again(tmp_path):
    """ROUND 2 FINDING (Important): `//!` is Rust's inner doc-comment marker --
    ordinary prose, exactly what this tool exists to review. The old bare
    `[!+]` alternative (meant only for SQL `/*!` and `/*+`) matched it on any
    opener, silently excluding every crate/module doc comment from review."""
    target = write(tmp_path, "z.rs", "fn f() {}\n\n//! crate docs\n")
    assert skips(target)["//! crate docs"] is None


def test_go_plus_one_prose_is_reviewable_again(tmp_path):
    """`// +1 to that` is ordinary prose, not a directive. This one was not
    actually reachable through the bare `[!+]` alternative -- it matched via
    the pre-existing `\\+\\w` alternative (a digit is a word character), a
    second, narrower over-broad match uncovered while verifying this finding
    by execution rather than taking the stated single-line fix at face value.
    Fixed by requiring 2+ word characters after `+` (`\\+\\w{2,}`), which
    excludes single-token "+1"/"+x" while still matching "+goose",
    "+kubebuilder", "+migrate", "+build"."""
    target = write(tmp_path, "z.go", "package p\n\n// +1 to that\n")
    assert skips(target)["// +1 to that"] is None


def test_shell_plus_x_prose_is_reviewable_again(tmp_path):
    """Same root cause as the +1 case above: `# +x is fine` matched via
    `\\+\\w` (a single letter is still \\w), not via the bare `[!+]`."""
    target = write(tmp_path, "s.sh", "echo hi\n\n# +x is fine\n")
    assert skips(target)["# +x is fine"] is None


def test_c_plus_minus_tolerance_prose_is_reviewable_again(tmp_path):
    """`/* +/- tolerance */` starts with the SQL-hint opener shape but has a
    space before the `+`, and the character right after `+` is `/`, not a
    word character -- neither the opener-specific `/\\*[!+]` (which requires
    no space) nor `\\+\\w{2,}` fires, so it correctly falls through to None."""
    target = write(tmp_path, "z.c", "int x;\n\n/* +/- tolerance */\n")
    assert skips(target)["/* +/- tolerance */"] is None


def test_banner_comment_is_reviewable_again(tmp_path):
    """Extra case from the coordinator's measured blast radius (not in the
    explicit verify-list, but the same bug): a banner/separator comment
    starting with `+` right after the opener, with no word character
    following, must not be treated as a directive."""
    target = write(tmp_path, "z.go", "package p\n\n// +----- separator --+\n")
    assert skips(target)["// +----- separator --+"] is None


def test_sql_optimizer_hint_still_protected_after_narrowing(tmp_path):
    """Regression: narrowing `[!+]` to be opener-specific (`/\\*[!+]`, no
    space) must not stop the SQL hint case it was written for."""
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n/*+ INDEX(t idx) */\n")
    assert skips(target)["/*+ INDEX(t idx) */"] == "directive"


def test_mysql_version_gate_still_protected_after_narrowing(tmp_path):
    """Regression: same as above for the MySQL version-gated comment."""
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n/*!50001 col */\n")
    assert skips(target)["/*!50001 col */"] == "directive"


def test_kubebuilder_marker_still_protected_after_tightening_plus_word(tmp_path):
    """Regression: tightening `\\+\\w` to `\\+\\w{2,}` (to exclude "+1"/"+x")
    must not stop `+kubebuilder`, a multi-character identifier."""
    target = write(tmp_path, "t.go", "package p\n\n// +kubebuilder:validation:Required\n")
    assert skips(target)["// +kubebuilder:validation:Required"] == "directive"


def test_build_constraint_still_protected_after_tightening_plus_word(tmp_path):
    """Regression: same as above for a Go build constraint."""
    target = write(tmp_path, "b.go", "package p\n\n// +build !windows\n")
    assert skips(target)["// +build !windows"] == "directive"

