from pathlib import Path

import extract_comments as ec


def write(tmp_path, name, text):
    target = tmp_path / name
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    return target


def skips(target):
    return {c["text"]: c["skip"] for c in ec.extract(target)["comments"]}


def test_generated_marker_skips_the_whole_file(tmp_path):
    target = write(tmp_path, "z.go", "// Code generated by protoc. DO NOT EDIT.\n// x\n")
    assert ec.extract(target)["skipped"] == "generated"


def test_vendor_path_skips_the_whole_file(tmp_path):
    target = write(tmp_path, "vendor/lib/z.go", "// x\n")
    assert ec.extract(target)["skipped"] == "excluded-path"


def test_fixture_path_skips_the_whole_file(tmp_path):
    target = write(tmp_path, "testdata/z.go", "// x\n")
    assert ec.extract(target)["skipped"] == "excluded-path"


def test_snapshot_suffix_skips_the_whole_file(tmp_path):
    target = write(tmp_path, "a.snap", "// x\n")
    assert ec.extract(target)["skipped"] in ("excluded-path", "unknown-language")


def test_first_two_lines_are_position_locked(tmp_path):
    target = write(tmp_path, "s.sh", "#!/usr/bin/env bash\n# -*- coding: utf-8 -*-\n# free\n")
    result = skips(target)
    assert result["#!/usr/bin/env bash"] == "position-locked"
    assert result["# -*- coding: utf-8 -*-"] == "position-locked"
    assert result["# free"] is None


def test_nolint_directive_is_protected(tmp_path):
    target = write(tmp_path, "z.go", "package p\n\nvar x = 1 //nolint:errcheck\n")
    assert skips(target)["//nolint:errcheck"] == "directive"


def test_eslint_disable_is_protected(tmp_path):
    target = write(tmp_path, "z.ts", "let a = 1;\n\n// eslint-disable-next-line no-eval\n")
    assert skips(target)["// eslint-disable-next-line no-eval"] == "directive"


def test_coverage_pragma_is_protected(tmp_path):
    target = write(tmp_path, "z.py", "x = 1\n\nif x:  # pragma: no cover\n    pass\n")
    assert skips(target)["# pragma: no cover"] == "directive"


def test_goose_migration_marker_is_protected(tmp_path):
    target = write(tmp_path, "m.sql", "SELECT 1;\n\n-- +goose Down\nDROP TABLE t;\n")
    assert skips(target)["-- +goose Down"] == "directive"


def test_sqlc_name_header_is_protected(tmp_path):
    target = write(tmp_path, "q.sql", "SELECT 1;\n\n-- name: GetUser :one\n")
    assert skips(target)["-- name: GetUser :one"] == "directive"


def test_kubebuilder_marker_is_protected(tmp_path):
    target = write(tmp_path, "t.go", "package p\n\n// +kubebuilder:validation:Required\n")
    assert skips(target)["// +kubebuilder:validation:Required"] == "directive"


def test_doctest_marker_protects_the_docstring(tmp_path):
    target = write(tmp_path, "d.py", 'x = 1\n\n\ndef f():\n    """Doc.\n\n    >>> f()\n    1\n    """\n')
    assert any(v == "test-oracle" for v in skips(target).values())


def test_go_output_marker_protects_the_comment(tmp_path):
    target = write(tmp_path, "e.go", "package p\n\n// Output:\n// 42\n")
    assert skips(target)["// Output:"] == "test-oracle"


def test_spdx_and_licence_are_protected(tmp_path):
    target = write(tmp_path, "l.go", "// SPDX-License-Identifier: MIT\n// Copyright 2026 X\n")
    result = skips(target)
    assert all(v is not None for v in result.values())


def test_protected_prefix_note_is_marked_not_deletable(tmp_path):
    target = write(tmp_path, "n.go", "package p\n\n// NOTE: retry twice, upstream 502s\n")
    assert skips(target)["// NOTE: retry twice, upstream 502s"] == "protected-prefix"


def test_ordinary_comment_is_not_skipped(tmp_path):
    target = write(tmp_path, "p.go", "package p\n\n// ordinary explanation\n")
    assert skips(target)["// ordinary explanation"] is None


def test_the_plugins_own_samples_are_not_excluded():
    """tests/samples/ must stay outside the skip patterns. When the directory was
    named fixtures/ it matched, and every extractor assertion silently went vacuous."""
    import paths
    assert ec.file_skip_reason(paths.SAMPLES / "sample.go", "") is None


def test_a_fixtures_path_is_still_excluded(tmp_path):
    """The pattern itself is correct and spec-mandated -- only our own directory
    name was wrong."""
    assert ec.file_skip_reason(tmp_path / "fixtures" / "z.go", "") == "excluded-path"


def test_a_repo_living_under_a_skip_named_directory_is_not_skipped(tmp_path, monkeypatch):
    """A checkout at ~/build/proj must not skip every file in itself."""
    repo = tmp_path / "build" / "proj" / "pkg"
    repo.mkdir(parents=True)
    target = repo / "z.go"
    target.write_text("package p\n\n// ordinary\n")
    monkeypatch.chdir(repo.parent)
    assert ec.extract(target)["skipped"] is None


def test_dockerfile_syntax_directive_is_protected(tmp_path):
    target = write(tmp_path, "Dockerfile.sh", "# syntax=docker/dockerfile:1\n# free\n")
    assert skips(target)["# syntax=docker/dockerfile:1"] == "position-locked"
